#!/usr/bin/env python3
"""
pac.py
------
Phase-Amplitude Coupling (PAC) between pain matrix regions
for the laser-pain MEG study.

Method: Tort et al. (2010) Modulation Index (MI)
    - Bandpass filter to phase-frequency band  → instantaneous phase (Hilbert)
    - Bandpass filter to amplitude-frequency band → amplitude envelope (Hilbert)
    - Bin phase into N = 18 bins of 20° each  (-π … π)
    - Compute mean amplitude per bin  →  normalise to probability distribution p(φ)
    - MI = (log N − H(p)) / log N      (H = Shannon entropy)
      MI ≈ 0 → uniform / no PAC;  MI → 1 → maximal PAC.

Directionality
    For every ROI pair (A, B) and every (phase_band × amp_band) combination,
    PAC is computed in BOTH directions independently:
        A → B   phase of A modulates amplitude of B
        B → A   phase of B modulates amplitude of A

Statistics
    Surrogate MI values are generated by randomly time-shifting the amplitude
    envelope (N_SURROGATES = 200, minimum shift = 1 s) on the concatenated
    trial signal to build a null distribution.
    Reported: MI_obs (raw),  z = (MI_obs − μ_surr) / σ_surr.

Input
    ROI time courses are read from the WPLI HDF5 file produced by wpli.py
    (group "roi_time_courses") to avoid re-running the inverse.  If the WPLI
    file is absent, use --from-scratch to compute the inverse from epochs.

Output
    derivatives/connectivity/<sub>/task-<task>/
        <sub>_task-<task>_pac_painmatrix.h5

HDF5 layout
    /{phase_roi}_to_{amp_roi}/phase_{band}_amp_{band}/{condition}/
        attrs: mi, z_score, surr_mean, surr_std
    /roi_time_courses/   (data, times, roi_names, conditions)

ROI definitions
    Loaded from core.py ATLAS_CONFIGS, identical to wpli.py.

Reference
    Tort AB et al. (2010). Measuring phase-amplitude coupling between
    neuronal oscillations of different frequencies.
    J Neurophysiol 104(2):1195-210. doi:10.1152/jn.00106.2010

Usage
-----
    python pac.py --subjects 4382
    python pac.py --tasks laser pinprick
    python pac.py --phase-bands theta --amp-bands gamma
    python pac.py --from-scratch          # recompute inverse instead of reading WPLI HDF5
    python pac.py --overwrite
"""

import argparse
import itertools
import sys
from pathlib import Path

import h5py
import mne
import numpy as np
from scipy.signal import butter, filtfilt, hilbert

from core import (
    ATLAS_CONFIGS,
    DEFAULT_ATLAS,
    DEFAULT_EPOCH_CONFIG,
    EPOCH_CONFIGS,
    TASKS,
    Paths,
    load_subjects,
    setup_logging,
    sub_id,
)

# Re-use helpers from wpli.py to keep definitions in sync
from connectivity_common import (
    _bandpass,
    _exists,
    _get_roi_pairs,
    extract_roi_time_courses,
    load_roi_labels,
)

DEFAULT_ROOT = Path("/Volumes/ExtremePro/laser")

# ---------------------------------------------------------------------------
# PAC frequency band definitions
# ---------------------------------------------------------------------------

PAC_PHASE_BANDS: dict[str, tuple[float, float]] = {
    "theta": (4.0, 8.0),
    "alpha": (8.0, 12.0),
}

PAC_AMP_BANDS: dict[str, tuple[float, float]] = {
    "beta": (15.0, 30.0),
    "gamma": (30.0, 80.0),
}

# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------

SNR = 3.0
LAMBDA2 = 1.0 / SNR**2
N_BINS = 18  # phase bins, 20° each → covers −π … π uniformly
N_SURROGATES = 200  # surrogate iterations for z-score normalisation
MIN_SHIFT_S = 1.0  # minimum time-shift for surrogate generation (seconds)


# ---------------------------------------------------------------------------
# Load ROI time courses from existing WPLI HDF5
# ---------------------------------------------------------------------------


def _load_tc_from_wpli(
    wpli_file: Path,
) -> tuple[np.ndarray, np.ndarray, list[str], list[str]]:
    """Read stored ROI time courses from a WPLI HDF5 file.

    Parameters
    ----------
    wpli_file : Path   Path to the wpli_painmatrix.h5 produced by wpli.py.

    Returns
    -------
    data       : np.ndarray  shape (n_rois, n_epochs, n_times)
    times      : np.ndarray  shape (n_times,)
    roi_names  : list[str]
    conditions : list[str]   condition label per epoch
    """
    with h5py.File(wpli_file, "r") as f:
        grp = f["roi_time_courses"]
        data = grp["data"][:]
        times = grp["times"][:]
        roi_names = [n.decode() for n in grp["roi_names"][:]]
        conditions = [c.decode() for c in grp["conditions"][:]]
    return data, times, roi_names, conditions


# ---------------------------------------------------------------------------
# Core PAC estimator (Tort et al. 2010)
# ---------------------------------------------------------------------------


def compute_tort_mi(
    phase: np.ndarray, amplitude: np.ndarray, n_bins: int = N_BINS
) -> float:
    """Tort et al. (2010) Modulation Index for 1-D phase and amplitude arrays.

    Parameters
    ----------
    phase     : np.ndarray  Instantaneous phase in radians  (−π … π), length N.
    amplitude : np.ndarray  Instantaneous amplitude envelope, length N.
    n_bins    : int         Number of phase bins (default 18 → 20° resolution).

    Returns
    -------
    float  MI in [0, 1].
    """
    edges = np.linspace(-np.pi, np.pi, n_bins + 1)
    amp_means = np.zeros(n_bins)
    for k in range(n_bins):
        mask = (phase >= edges[k]) & (phase < edges[k + 1])
        if mask.any():
            amp_means[k] = amplitude[mask].mean()

    total = amp_means.sum()
    if total < 1e-12:
        return 0.0

    p = amp_means / total
    p_nz = p[p > 0]
    H = -np.sum(p_nz * np.log(p_nz))
    return float((np.log(n_bins) - H) / np.log(n_bins))


def compute_pac_with_surrogates(
    tc_phase_roi: np.ndarray,
    tc_amp_roi: np.ndarray,
    sfreq: float,
    phase_band: tuple[float, float],
    amp_band: tuple[float, float],
    n_bins: int = N_BINS,
    n_surrogates: int = N_SURROGATES,
    rng_seed: int = 42,
) -> tuple[float, float, float, float]:
    """Compute Tort MI and surrogate z-score for one directed PAC pair.

    Trials are concatenated before MI estimation (more data → more reliable
    phase binning) and the surrogate null distribution is built by randomly
    time-shifting the amplitude envelope on the concatenated signal.

    Parameters
    ----------
    tc_phase_roi : np.ndarray  shape (n_trials, n_times)  —  source of phase
    tc_amp_roi   : np.ndarray  shape (n_trials, n_times)  —  source of amplitude
    sfreq        : float       Sampling frequency in Hz.
    phase_band   : tuple       (lo_hz, hi_hz) for phase extraction.
    amp_band     : tuple       (lo_hz, hi_hz) for amplitude extraction.
    n_bins       : int         Phase bins (default N_BINS).
    n_surrogates : int         Surrogate iterations (default N_SURROGATES).
    rng_seed     : int         NumPy random seed for reproducibility.

    Returns
    -------
    (mi_obs, z_score, surr_mean, surr_std)
    """
    lo_p, hi_p = phase_band
    lo_a, hi_a = amp_band
    n_trials = tc_phase_roi.shape[0]

    # --- per-trial filter + Hilbert → concatenate ---
    phase_list, amp_list = [], []
    for ei in range(n_trials):
        sig_p = _bandpass(tc_phase_roi[ei], lo_p, hi_p, sfreq)
        sig_a = _bandpass(tc_amp_roi[ei], lo_a, hi_a, sfreq)
        phase_list.append(np.angle(hilbert(sig_p)))
        amp_list.append(np.abs(hilbert(sig_a)))

    phase_cat = np.concatenate(phase_list)
    amp_cat = np.concatenate(amp_list)
    n_total = len(phase_cat)

    # --- observed MI ---
    mi_obs = compute_tort_mi(phase_cat, amp_cat, n_bins)

    # --- surrogate distribution (random time-shift of amplitude) ---
    min_shift = max(1, int(MIN_SHIFT_S * sfreq))
    max_shift = n_total - min_shift
    if max_shift <= min_shift:
        # signal too short for meaningful surrogates
        return mi_obs, np.nan, np.nan, np.nan

    rng = np.random.default_rng(rng_seed)
    shifts = rng.integers(min_shift, max_shift, size=n_surrogates)
    surr_mis = np.array(
        [compute_tort_mi(phase_cat, np.roll(amp_cat, sh), n_bins) for sh in shifts]
    )

    surr_mean = surr_mis.mean()
    surr_std = surr_mis.std()
    z = (mi_obs - surr_mean) / surr_std if surr_std > 1e-12 else 0.0

    return float(mi_obs), float(z), float(surr_mean), float(surr_std)


# ---------------------------------------------------------------------------
# Per-subject / task orchestration
# ---------------------------------------------------------------------------


def pac_one(
    paths: Paths,
    label: str,
    task: str,
    epoch_config: str,
    phase_bands: list[str],
    amp_bands: list[str],
    atlas_key: str = DEFAULT_ATLAS,
    overwrite: bool = False,
    from_scratch: bool = False,
    trial_filter: str = "all",
    logger=None,
) -> bool:
    """Compute PAC for all ROI pairs, directions, and band combinations.

    Parameters
    ----------
    paths        : Paths
    label        : str    Bare subject label.
    task         : str
    epoch_config : str
    phase_bands  : list[str]  Keys from PAC_PHASE_BANDS.
    amp_bands    : list[str]  Keys from PAC_AMP_BANDS.
    atlas_key    : str
    overwrite    : bool
    from_scratch : bool   Recompute inverse rather than loading from WPLI HDF5.
    logger       :

    Returns
    -------
    bool  True on success.
    """
    tag = f"sub-{label} / {task}"
    out_dir = paths.deriv / "connectivity" / sub_id(label) / f"task-{task}"
    suffix   = "" if trial_filter == "all" else f"_{trial_filter}"
    out_file = out_dir / f"{sub_id(label)}_task-{task}_pac_painmatrix{suffix}.h5"

    if _exists(out_file) and not overwrite:
        logger.info("[%s]  SKIP — PAC file exists", tag)
        return True

    # ------------------------------------------------------------------
    # Load ROI time courses
    # ------------------------------------------------------------------
    wpli_file = out_dir / f"{sub_id(label)}_task-{task}_wpli_painmatrix.h5"
    data: np.ndarray | None = None

    if not from_scratch and _exists(wpli_file):
        logger.info("[%s]  Reading ROI time courses from WPLI HDF5 ...", tag)
        try:
            data, times, roi_names, conditions = _load_tc_from_wpli(wpli_file)
            logger.info("[%s]  TC shape: %s  ROIs: %s", tag, data.shape, roi_names)
        except Exception as exc:
            logger.warning(
                "[%s]  Could not read WPLI HDF5 (%s) — falling back to inverse",
                tag,
                exc,
            )
            data = None

    if data is None:
        logger.info("[%s]  Computing ROI time courses from inverse ...", tag)
        inv_file = paths.inv(label, task)
        if not _exists(inv_file):
            logger.warning("[%s]  Inverse operator not found: %s", tag, inv_file)
            return False

        inv = mne.minimum_norm.read_inverse_operator(str(inv_file), verbose=False)
        roi_label_map = load_roi_labels(paths, label, logger, atlas_key=atlas_key)
        if len(roi_label_map) < 2:
            logger.warning("[%s]  Too few ROIs matched — skipping", tag)
            return False

        result = extract_roi_time_courses(
            paths, label, task, epoch_config, inv, roi_label_map, logger,
            trial_filter=trial_filter,
        )
        if result is None:
            return False
        data, times, roi_names, conditions = result

    sfreq = round(1.0 / float(times[1] - times[0]))
    unique_conditions = sorted(set(conditions))
    roi_pairs = _get_roi_pairs(roi_names)
    pac_combos = list(itertools.product(phase_bands, amp_bands))

    n_directions = len(roi_pairs) * 2  # both directions per pair
    logger.info(
        "[%s]  PAC: %d directions × %d band combos × %d conditions",
        tag,
        n_directions,
        len(pac_combos),
        len(unique_conditions),
    )

    # ------------------------------------------------------------------
    # Compute PAC for all directions / band combos / conditions
    # ------------------------------------------------------------------

    # Structure: results[direction][combo][cond] = (mi, z, surr_mean, surr_std)
    pac_results: dict[str, dict[str, dict[str, tuple]]] = {}

    for roi_a, roi_b in roi_pairs:
        if roi_a not in roi_names or roi_b not in roi_names:
            logger.warning("[%s]  Pair %s-%s: ROI missing", tag, roi_a, roi_b)
            continue

        idx_a = roi_names.index(roi_a)
        idx_b = roi_names.index(roi_b)

        # Both directions: A → B  and  B → A
        for phase_roi, amp_roi, phase_idx, amp_idx in [
            (roi_a, roi_b, idx_a, idx_b),
            (roi_b, roi_a, idx_b, idx_a),
        ]:
            direction = f"{phase_roi}_to_{amp_roi}"
            pac_results[direction] = {}

            for p_name, a_name in pac_combos:
                combo_key = f"phase_{p_name}_amp_{a_name}"
                pac_results[direction][combo_key] = {}

                for cond in unique_conditions:
                    mask = np.array([c == cond for c in conditions])
                    tc_ph = data[phase_idx, mask, :].astype(np.float64)
                    tc_am = data[amp_idx, mask, :].astype(np.float64)

                    if tc_ph.shape[0] < 5:
                        logger.warning(
                            "[%s]  %s / %s / %s: only %d trials — skip",
                            tag,
                            direction,
                            combo_key,
                            cond,
                            tc_ph.shape[0],
                        )
                        pac_results[direction][combo_key][cond] = (
                            np.nan,
                            np.nan,
                            np.nan,
                            np.nan,
                        )
                        continue

                    mi, z, surr_mean, surr_std = compute_pac_with_surrogates(
                        tc_ph,
                        tc_am,
                        sfreq,
                        PAC_PHASE_BANDS[p_name],
                        PAC_AMP_BANDS[a_name],
                    )
                    pac_results[direction][combo_key][cond] = (
                        mi,
                        z,
                        surr_mean,
                        surr_std,
                    )
                    logger.info(
                        "[%s]  %-30s  %-30s  %-20s  MI=%.4f  z=%+.2f  (n=%d)",
                        tag,
                        direction,
                        combo_key,
                        cond,
                        mi,
                        z,
                        tc_ph.shape[0],
                    )

    # ------------------------------------------------------------------
    # Save to HDF5
    # ------------------------------------------------------------------
    out_dir.mkdir(parents=True, exist_ok=True)

    def _safe_float(v) -> float:
        return float(v) if (v is not None and not np.isnan(v)) else np.nan

    with h5py.File(out_file, "w") as f:
        f.attrs["subject"] = sub_id(label)
        f.attrs["task"] = task
        f.attrs["epoch_config"] = epoch_config
        f.attrs["atlas"] = atlas_key
        f.attrs["method"] = "PAC-TortMI"
        f.attrs["reference"] = "Tort et al. 2010 J Neurophysiol 104:1195"
        f.attrs["n_bins"] = N_BINS
        f.attrs["n_surrogates"] = N_SURROGATES
        f.attrs["min_shift_s"] = MIN_SHIFT_S
        f.attrs["sfreq"] = sfreq

        for direction, combo_dict in pac_results.items():
            dgrp = f.create_group(direction)
            for combo_key, cond_dict in combo_dict.items():
                cgrp = dgrp.create_group(combo_key)
                for cond, (mi, z, surr_mean, surr_std) in cond_dict.items():
                    sgrp = cgrp.create_group(cond)
                    sgrp.attrs["mi"] = _safe_float(mi)
                    sgrp.attrs["z_score"] = _safe_float(z)
                    sgrp.attrs["surr_mean"] = _safe_float(surr_mean)
                    sgrp.attrs["surr_std"] = _safe_float(surr_std)

        # Store ROI time courses for downstream use (mirrors wpli.py)
        tc_grp = f.create_group("roi_time_courses")
        tc_grp.create_dataset("data", data=data, compression="gzip", compression_opts=4)
        tc_grp.create_dataset("times", data=times)
        tc_grp.create_dataset("roi_names", data=np.array(roi_names, dtype="S"))
        tc_grp.create_dataset("conditions", data=np.array(conditions, dtype="S"))

    logger.info("[%s]  Saved: %s", tag, out_file.name)
    return True


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Phase-Amplitude Coupling (Tort MI) between pain matrix regions "
            "for the laser-pain MEG study."
        )
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=DEFAULT_ROOT,
        help=f"BIDS project root (default: {DEFAULT_ROOT})",
    )
    parser.add_argument(
        "--subjects",
        nargs="+",
        default=None,
        metavar="LABEL",
        help="Bare subject labels (default: all in participants.tsv)",
    )
    parser.add_argument(
        "--tasks",
        nargs="+",
        default=None,
        choices=TASKS,
        metavar="TASK",
        help=f"Tasks to process (default: all — {TASKS})",
    )
    parser.add_argument(
        "--epoch-config",
        default="sweep-tfr",
        choices=list(EPOCH_CONFIGS.keys()),
        help="Epoch configuration (default: sweep-tfr for broadband PAC)",
    )
    parser.add_argument(
        "--phase-bands",
        nargs="+",
        default=list(PAC_PHASE_BANDS.keys()),
        choices=list(PAC_PHASE_BANDS.keys()),
        help=f"Phase-frequency bands (default: all — {list(PAC_PHASE_BANDS.keys())})",
    )
    parser.add_argument(
        "--amp-bands",
        nargs="+",
        default=list(PAC_AMP_BANDS.keys()),
        choices=list(PAC_AMP_BANDS.keys()),
        help=f"Amplitude-frequency bands (default: all — {list(PAC_AMP_BANDS.keys())})",
    )
    parser.add_argument(
        "--atlas",
        default=DEFAULT_ATLAS,
        choices=list(ATLAS_CONFIGS.keys()),
        help=f"Atlas configuration from core.py (default: {DEFAULT_ATLAS})",
    )
    parser.add_argument(
        "--from-scratch",
        action="store_true",
        default=True,
        help=(
            "Always recompute ROI time courses from the inverse operator "
            "instead of reading from the WPLI HDF5 file."
        ),
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing PAC files",
    )
    parser.add_argument(
        "--trials", default="all", choices=["all", "perceived", "not-perceived"],
        help=(
            "'all' = all epochs (default). "
            "'perceived' = only trials rated > 0 and not 'miss'. "
            "'not-perceived' = only trials rated exactly 0 and not 'miss'. "
            "Requires match_ratings.py first. "
            "Output gets a matching suffix so all versions coexist."
        ),
    )
    parser.add_argument(
        "--metric",
        default="z_score",
        choices=["z_score", "mi"],
        help="PAC metric to plot: 'z_score' (default) or raw 'mi'",
    )
    parser.add_argument(
        "--plot",
        action="store_true",
        help=(
            "Save all PAC plots as PNGs (comodulogram + directionality + raincloud). "
            "Does not recompute — reads existing HDF5 files."
        ),
    )
    parser.add_argument(
        "--plot-comodulogram",
        action="store_true",
        help="Save comodulogram plots only (phase × amplitude heatmap).",
    )
    parser.add_argument(
        "--plot-directionality",
        action="store_true",
        help="Save directionality contrast plots only (A→B vs B→A bar chart).",
    )
    parser.add_argument(
        "--plot-raincloud",
        action="store_true",
        help="Save raincloud plots only (subject-level z-score distributions).",
    )
    parser.add_argument(
        "--plot-show",
        action="store_true",
        help="Open the plots folder in Finder after saving. Use together with --plot.",
    )
    args = parser.parse_args()

    paths = Paths(args.root)
    logger = setup_logging(paths, "pac")

    subjects = args.subjects if args.subjects else load_subjects(paths)
    tasks = args.tasks if args.tasks else TASKS

    # ── Plot modes ───────────────────────────────────────────────────────
    any_plot = (
        args.plot
        or args.plot_comodulogram
        or args.plot_directionality
        or args.plot_raincloud
    )

    if any_plot or args.plot_show:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        from plot_pac import (
            _all_combos,
            _all_directions,
            load_pac_matrix,
            plot_comodulograms,
            plot_directionality,
            plot_raincloud,
        )

        out_dir_base = paths.log_dir() / "plots" / "pac"
        out_dir_base.mkdir(parents=True, exist_ok=True)

        if args.plot_show and not any_plot:
            import subprocess

            logger.info("Opening plots folder: %s", out_dir_base)
            subprocess.run(["open", str(out_dir_base)])
            return

        do_como = args.plot or args.plot_comodulogram
        do_dir = args.plot or args.plot_directionality
        do_rain = args.plot_raincloud  # raincloud is opt-in only

        logger.info("-- PAC plot mode --")
        logger.info("Subjects : %s", subjects)
        logger.info("Tasks    : %s", tasks)
        logger.info("Metric   : %s", args.metric)

        for label in subjects:
            # Per-subject output folder
            out_dir = out_dir_base / f"sub-{label}"
            out_dir.mkdir(parents=True, exist_ok=True)

            data, directions, combos = load_pac_matrix(
                paths,
                [label],
                tasks,
                args.phase_bands,
                args.amp_bands,
                args.atlas,
                args.metric,
            )

            active_dirs = [
                d
                for d in directions
                if any(
                    not np.all(np.isnan(data[t][d][c])) for t in tasks for c in combos
                )
            ]

            if not active_dirs:
                logger.warning("[sub-%s]  No PAC data found — skipping", label)
                continue

            logger.info("[sub-%s]  Active directions: %d", label, len(active_dirs))

            if do_como:
                logger.info("[sub-%s]  Generating comodulograms ...", label)
                plot_comodulograms(
                    data,
                    active_dirs,
                    combos,
                    args.phase_bands,
                    args.amp_bands,
                    tasks,
                    out_dir,
                    args.metric,
                    subject_label=label,
                )

            if do_dir:
                logger.info("[sub-%s]  Generating directionality plots ...", label)
                plot_directionality(
                    data,
                    active_dirs,
                    combos,
                    tasks,
                    out_dir,
                    args.metric,
                    subject_label=label,
                )

            if do_rain:
                logger.info("[sub-%s]  Generating raincloud plots ...", label)
                for direction in active_dirs:
                    for combo in combos:
                        plot_raincloud(
                            data,
                            direction,
                            combo,
                            tasks,
                            out_dir,
                            args.metric,
                            subject_label=label,
                        )

            logger.info("[sub-%s]  Plots saved to: %s", label, out_dir)

        if args.plot_show:
            import subprocess

            logger.info("Opening plots folder ...")
            subprocess.run(["open", str(out_dir_base)])

        return

    # ── Compute mode ─────────────────────────────────────────────────────
    combos = list(itertools.product(args.phase_bands, args.amp_bands))
    logger.info("Subjects      : %s", subjects)
    logger.info("Tasks         : %s", tasks)
    logger.info("Epoch config  : %s", args.epoch_config)
    logger.info(
        "Phase bands   : %s  %s",
        args.phase_bands,
        {b: PAC_PHASE_BANDS[b] for b in args.phase_bands},
    )
    logger.info(
        "Amp bands     : %s  %s",
        args.amp_bands,
        {b: PAC_AMP_BANDS[b] for b in args.amp_bands},
    )
    logger.info(
        "Combinations  : %d  %s",
        len(combos),
        [f"phase_{p}_amp_{a}" for p, a in combos],
    )
    logger.info("Atlas         : %s", args.atlas)
    logger.info("From scratch  : %s", args.from_scratch)
    logger.info("Overwrite     : %s", args.overwrite)
    logger.info("Trials        : %s", args.trials)

    n_ok, n_fail = 0, 0

    for label in subjects:
        for task in tasks:
            try:
                ok = pac_one(
                    paths,
                    label,
                    task,
                    epoch_config=args.epoch_config,
                    phase_bands=args.phase_bands,
                    amp_bands=args.amp_bands,
                    atlas_key=args.atlas,
                    overwrite=args.overwrite,
                    from_scratch=args.from_scratch,
                    trial_filter=args.trials,
                    logger=logger,
                )
                if ok:
                    n_ok += 1
                else:
                    n_fail += 1
            except Exception as exc:
                logger.error(
                    "[sub-%s / %s]  FAILED: %s", label, task, exc, exc_info=True
                )
                n_fail += 1

    logger.info("─────────────────────────────────────────────")
    logger.info("Done.  Success: %d  |  Failed: %d", n_ok, n_fail)

    if n_fail > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
